# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CD

on:
  release:

jobs:
  release:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm run package -- win32
    - uses: PeerXu/upload-asset@v1
      with:
        file: ${{ github.workspace }}\dist\WebTorrent-win32-x64\WebTorrent.exe
        os: windows
        arch: amd64
        with_tag: true 
        with_sha1: true 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
